import type { Project, ProjectQuickLinks } from './types';

function instagramFromUsername(username: string): string {
  const handle = username.replace(/^@/, '');
  return `https://instagram.com/${handle}`;
}

function defaultQuickLinks(username: string, slug: string): ProjectQuickLinks {
  return {
    instagram: instagramFromUsername(username),
    facebookAds: `https://business.facebook.com/adsmanager/manage/campaigns?project=${slug}`,
    googleDrive: `https://drive.google.com/drive/folders/${slug}`,
  };
}

export const projects: Project[] = [
  {
    id: 'black-ritual',
    username: '@black.ritual.kyiv',
    name: 'Black Ritual Studio',
    role: 'Blackwork',
    tier: 'L80',
    hue: 20,
    status: 'active',
    city: 'Київ, UA',
    birthday: '14.06.1991',
    joined: '12.01.2022',
    conditions: 'Студія · 3 кресла. Пріоритет на великі плечі та спину, бронь за 2 тижні.',
    dream: 'Відкрити другу локацію у Львові',
    hobby: 'Гравюра, джаз',
    email: 'hello@blackritual.ink',
    phone: '+380 67 100 22 11',
    telegram: '@black_ritual',
    telegramId: '671002211',
    comments: 'Флагманський проєкт мережі Digital Ink.',
    quickLinks: defaultQuickLinks('@black.ritual.kyiv', 'black-ritual'),
  },
  {
    id: 'vlad-ink',
    username: '@vlad.ink',
    name: 'Влад «Ink» Коваленко',
    role: 'Realism',
    tier: 'L70',
    hue: 200,
    status: 'active',
    city: 'Київ, UA',
    birthday: '03.11.1993',
    joined: '04.03.2022',
    conditions: 'Майстер · 45% від чека. Портрети та cover-up, очікування 3–4 міс.',
    dream: 'Конвенція Rome Ink Week',
    hobby: 'Фотографія, мото',
    email: 'vlad@digitalink.team',
    phone: '+380 93 555 18 40',
    telegram: '@vlad_ink',
    telegramId: '935551840',
    comments: 'Топ за відгуками клієнтів у 2025.',
    quickLinks: defaultQuickLinks('@vlad.ink', 'vlad-ink'),
  },
  {
    id: 'maya-lines',
    username: '@maya.lines',
    name: 'Maya Lines',
    role: 'Fine Line',
    tier: 'L60',
    hue: 340,
    status: 'active',
    city: 'Львів, UA',
    birthday: '22.08.1996',
    joined: '19.07.2023',
    conditions: 'Майстер · мінімалізм, рослинні орнаменти. Запис через Instagram DM.',
    dream: 'Колаборація з fashion-брендом',
    hobby: 'Акварель, подкасти',
    email: 'maya@digitalink.team',
    phone: '+380 67 880 12 09',
    telegram: '@maya_lines',
    telegramId: '678801209',
    comments: 'Високий repeat-rate по рекомендаціях.',
    quickLinks: defaultQuickLinks('@maya.lines', 'maya-lines'),
  },
  {
    id: 'old-sailor',
    username: '@old.sailor.od',
    name: 'Old Sailor · Одеса',
    role: 'Traditional',
    tier: 'L65',
    hue: 60,
    status: 'active',
    city: 'Одеса, UA',
    birthday: '09.02.1988',
    joined: '01.09.2021',
    conditions: 'Студія · old school / neo-trad. Walk-in по пʼятницях.',
    dream: 'Книга флешів власного авторства',
    hobby: 'Вітрила, вініл',
    email: 'book@oldsailor.ink',
    phone: '+380 48 700 33 21',
    telegram: '@old_sailor',
    telegramId: '487003321',
    comments: 'Найстаріший проєкт у портфелі.',
    quickLinks: defaultQuickLinks('@old.sailor.od', 'old-sailor'),
  },
  {
    id: 'neo-chrome',
    username: '@neo.chrome',
    name: 'Neo Chrome Lab',
    role: 'Cyber Sigil',
    tier: 'L55',
    hue: 280,
    status: 'paused',
    city: 'Харків, UA',
    birthday: '17.12.1994',
    joined: '11.02.2024',
    conditions: 'На паузі · релокація обладнання. Повернення Q3 2026.',
    dream: 'AR-превʼю тату перед сеансом',
    hobby: '3D, synthwave',
    email: 'lab@neochrome.ink',
    phone: '+380 50 412 90 77',
    telegram: '@neo_chrome',
    telegramId: '504129077',
    comments: 'Тимчасово без онлайн-запису.',
    quickLinks: defaultQuickLinks('@neo.chrome', 'neo-chrome'),
  },
  {
    id: 'sakura-hand',
    username: '@sakura.hand',
    name: 'Sakura Hand · Tokyo pop-up',
    role: 'Irezumi',
    tier: 'L75',
    hue: 160,
    status: 'active',
    city: 'Tokyo, JP',
    birthday: '30.04.1990',
    joined: '20.05.2024',
    conditions: 'Гостьовий майстер · 2 слоти на місяць, депозит 30%.',
    dream: 'Постійна студія в Києві',
    hobby: 'Чай, каліграфія',
    email: 'sakura@digitalink.team',
    phone: '+81 90 1234 5678',
    telegram: '@sakura_hand',
    telegramId: '9012345678',
    comments: 'Поп-ап формат, календар синхронізується вручну.',
    quickLinks: defaultQuickLinks('@sakura.hand', 'sakura-hand'),
  },
];
