import type { TeamMember } from './types';

export const teamMembers: TeamMember[] = [
  { id: 'andrii', username: 'a.melnyk', name: 'Андрій Мельник', role: 'Owner', tier: 'L100', hue: 20, status: 'active', city: 'Київ, UA', birthday: '12.03.1989', joined: '01.01.2022', conditions: 'Партнер · 28%. Доступний для стратегічних сесій і ревʼю ключових угод.', dream: 'Вивести Aurora на ринок EU за 18 місяців', hobby: 'Кросфіт, гірський велосипед', email: 'a.melnyk@aurora.co', phone: '+380 67 412 88 21', telegram: '@a_melnyk', telegramId: '74218821', comments: 'Фокус на стратегічних клієнтах і партнерських інтеграціях.' },
  { id: 'daria', username: 'd.vlasenko', name: 'Дарія Власенко', role: 'Senior Media Buyer', tier: 'L60', hue: 340, status: 'active', city: 'Львів, UA', birthday: '28.07.1994', joined: '03.04.2022', conditions: 'FTE · бонуси по KPI. Веде складні performance-кампанії.', dream: 'Закрити перший deal на $1M', hobby: 'Йога, кераміка', email: 'd.vlasenko@aurora.co', phone: '+380 63 221 70 04', telegram: '@d_vlasenko', telegramId: '632217004', comments: 'Потребує раннього доступу до нових рекламних кабінетів.' },
  { id: 'yaroslav', username: 'y.antonyuk', name: 'Ярослав Антонюк', role: 'Media Buyer', tier: 'L50', hue: 200, status: 'active', city: 'Одеса, UA', birthday: '09.11.1996', joined: '17.08.2023', conditions: 'FTE. Працює з холодними запусками та тестами креативів.', dream: 'Подорож у Патагонію', hobby: 'Серфінг, фото', email: 'y.antonyuk@aurora.co', phone: '+380 95 818 22 19', telegram: '@y_antonyuk', telegramId: '958182219', comments: 'Добре закриває задачі з короткими дедлайнами.' },
  { id: 'sofia', username: 's.beaumont', name: 'Sofia Beaumont', role: 'Project Manager', tier: 'L55', hue: 60, status: 'active', city: 'Paris, FR', birthday: '02.05.1992', joined: '12.01.2023', conditions: 'Контракт · part-time. Координує міжнародні проєкти й клієнтські апдейти.', dream: 'Запустити свій pod-cast', hobby: 'Гастро-блогінг', email: 'sofia.b@aurora.co', phone: '+33 6 18 24 90 11', telegram: '@s_beaumont', telegramId: '618249011', comments: 'Комунікація англійською та французькою.' },
  { id: 'oleksii', username: 'o.tkach', name: 'Олексій Ткач', role: 'Booking Manager', tier: 'L45', hue: 160, status: 'paused', city: 'Дніпро, UA', birthday: '17.02.1990', joined: '22.11.2022', conditions: 'FTE. На паузі до завершення внутрішнього переходу.', dream: 'Збудувати домик біля Карпат', hobby: 'Туризм, шахи', email: 'o.tkach@aurora.co', phone: '+380 50 412 09 88', telegram: '@o_tkach', telegramId: '504120988', comments: 'Повернути доступи після зміни статусу на active.' },
  { id: 'mira', username: 'm.halvorsen', name: 'Mira Halvorsen', role: 'Head of Project Manager', tier: 'L65', hue: 280, status: 'active', city: 'Oslo, NO', birthday: '24.09.1993', joined: '09.05.2024', conditions: 'FTE · стек. Відповідає за процеси, документацію та ритм команди.', dream: 'PhD у economics', hobby: 'Бігова дорога, нотатки', email: 'mira.h@aurora.co', phone: '+47 92 14 30 11', telegram: '@m_halvorsen', telegramId: '92143011', comments: 'Підтримує onboarding і стандарти delivery.' },
  { id: 'nina', username: 'n.kozak', name: 'Nina Kozak', role: 'Designer', tier: 'L50', hue: 310, status: 'active', city: 'Київ, UA', birthday: '03.08.1997', joined: '14.02.2024', conditions: 'FTE · дизайн-система, UI/UX, креативи для performance.', dream: 'Відкрити студію брендингу', hobby: 'Скетчинг, виставки', email: 'n.kozak@aurora.co', phone: '+380 93 550 12 44', telegram: '@n_kozak', telegramId: '935501244', comments: 'Веде візуальну частину ключових проєктів.' },
];
